#!/bin/bash

set -C -f
IFS="$(printf '%b_' '\n')"; IFS="${IFS%_}"

image() {
	#if [ -f "$1" ] && [ -n "$DISPLAY" ] && [ -z "$WAYLAND_DISPLAY" ] && command -V ueberzug >/dev/null 2>&1; then
		#if [ -n "${FIFO_UEBERZUG:-}" ] && [ -p "$FIFO_UEBERZUG" ]; then
			#width="$(( $2 - 1 ))"
			#height="$(( $3 - 1 ))"
			#if command -V timeout >/dev/null 2>&1; then
				#timeout 0.2s sh -c 'printf "{\"action\": \"add\", \"identifier\": \"PREVIEW\", \"x\": \"%s\", \"y\": \"%s\", \"width\": \"%s\", \"height\": \"%s\", \"scaler\": \"contain\", \"path\": \"%s\"}\\n\" "$1" "$2" "$3" "$4" "$5" > "$6"' sh "$4" "$5" "$width" "$height" "$1" "$FIFO_UEBERZUG"
			#else
				#printf '{"action": "add", "identifier": "PREVIEW", "x": "%s", "y": "%s", "width": "%s", "height": "%s", "scaler": "contain", "path": "%s"}\n' "$4" "$5" "$width" "$height" "$1" > "$FIFO_UEBERZUG"
			#fi
			#return 0
		#fi
	#fi
	if command -V chafa >/dev/null 2>&1; then
		chafa --fill=block --symbols=block -c 256 -s "${2}x${3}" "$1" || exit 1
	else
		mediainfo "$6"
	fi
}

# ANSI color codes are supported.
# STDIN is disabled, so interactive scripts won't work properly

# This script is considered a configuration file and must be updated manually.

# Meanings of exit codes:
# code | meaning    | action of ranger
# -----+------------+-------------------------------------------
# 0    | success    | Display stdout as preview
# 1    | no preview | Display no preview at all
# 2    | plain text | Display the plain content of the file

case "$(file --dereference --brief --mime-type -- "$1")" in
	text/html) lynx -width="$4" -display_charset=utf-8 -dump "$1" ;;
	text/troff) man ./ "${1}" | col -b ;;
	text/* | */xml | application/json | application/x-ndjson) bat -p --theme ansi --terminal-width "$(($4-2))" -f "$1" ;;
	audio/* | application/octet-stream) mediainfo "$1" || exit 1 ;;
	application/zip | application/x-tar | application/gzip ) atool --list -- "${1}" ;;
	#application/zip ) unzip -l "${1}" | head -n 200;;
	application/gzip | application/x-tar ) tar --list -f "${1}" | head -n 200 ;;
	#image/*) chafa --fill=block --symbols=block -c 256 -s 80x"${2}" "${1}" || exit 1;;
	image/*) image "$1" "$2" "$3" "$4" "$5" "$1" ;;
	video/* | audio/*|application/octet-stream) mediainfo "${1}" || exit 1;;
	*/pdf) pdftotext -l 10 -nopgbrk -q -- "${1}" - ;;
	*opendocument*) odt2txt "${1}" ;;
	*) head -n 100 "${1}" ;;
esac
exit 0
